name: static_analysis
on: [pull_request]
jobs:
  static_analysis:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: sudo apt install pcre
      - uses: mmomtchev/setup-swig@v1
        with:
          version: v3.0.12
          cache: true
      - run: pip install -r requirements.txt
      - run: python -m flake8
