name: static_analysis-unit_tests

on: [pull_request]

jobs:

  static_analysis:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libpcre3 libpcre3-dev

      - uses: mmomtchev/setup-swig@v1
        with:
          version: v3.0.12
          cache: true

      - run: pip install -r requirements.txt

      - run: python -m flake8

  unit_tests:
    # Reactivate these two lines if you get cryptic cache errors
    needs: static_analysis
    if: ${{ always() }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libpcre3 libpcre3-dev

      - uses: mmomtchev/setup-swig@v1
        with:
          version: v3.0.12
          token: ${{ github.token }}
          cache: true

      - run: pip install -r requirements.txt

      - run: python -m unittest tests/*.py
